# Generated by Django 5.0.6 on 2024-07-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField()),
                ('retailers_names', models.CharField(max_length=255)),
                ('retailer_industry', models.CharField(max_length=255)),
                ('country_of_opening', models.CharField(max_length=255)),
                ('number_of_stores', models.IntegerField()),
                ('summary_eng', models.CharField(max_length=100)),
            ],
        ),
    ]
